openapi: 3.0.3
info:
  title: NYC AirBnB Explorer
  description: REST API for Advanced Software Engineering FS21 Project
  version: 0.1.0
servers:
- url: /api/v1/airbnb-explorer
tags:
- name: Listings
  description: Endpoints to access AirBnB Listings
- name: Hosts
  description: Endpoints to access AirBnB Hosts
- name: Layers
  description: Endpoints to access AirBnB Listing geolocations for Layers
- name: Recommendations
  description: Endpoints for AirBnB Listing Recommendations
paths:
  /listings/metadata:
    get:
      tags:
        - Listings
      summary: Get metadata about listings
      description: Returns statistics about all listings
      operationId: get_metadata
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingsMetadata'
        "500":
          description: Internal Server Error
      x-openapi-router-controller: server.controllers.listings_controller
  /listings/{listingId}:
    get:
      tags:
      - Listings
      summary: Find Listing by ID
      description: Returns a single Listing matching the given ID
      operationId: find_listing_by_id
      parameters:
      - name: listingId
        in: path
        description: ID of Listing to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 2539
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        "400":
          description: Invalid ID supplied
        "404":
          description: Listing not found
      x-openapi-router-controller: server.controllers.listings_controller
  /listings:
    get:
      tags:
      - Listings
      summary: Retrieve NYC AirBnB listings
      description: Returns a list of AirBnB Listings based on the provided filter
        criteria
      operationId: find_listings
      parameters:
      - name: listingName
        in: query
        description: Name to match Listings (can bei either exact match or not)
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: hostId
        in: query
        description: Filter Listings based on hostId
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: hostName
        in: query
        description: Name to match Hosts of Listings (can bei either exact match or
          not)
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: location
        in: query
        description: Filter Listings by their location
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: area
        in: query
        description: Filter Listings by their area
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: priceMin
        in: query
        description: Filter Listings by minimum price
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: priceMax
        in: query
        description: Filter Listings by maximum price
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: minNights
        in: query
        description: Filter Listings by minimum nights
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: availability
        in: query
        description: Filter Listings by their availability
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: listingsPerHost
        in: query
        description: Filter Listings by the number of Listings per Host
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: roomType
        in: query
        description: Filter Listings by room type
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
                x-content-type: application/json
        "400":
          description: Invalid input
        "404":
          description: Listing not found
      x-openapi-router-controller: server.controllers.listings_controller
  /listings/{listingId}/reviews:
    get:
      tags:
      - Listings
      summary: Find Reviews for a given Listing
      description: Returns all Reviews for a single Listing matching the given ID
      operationId: find_reviews_for_listing
      parameters:
      - name: listingId
        in: path
        description: ID of Listing to return Reviews
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
                x-content-type: application/json
        "400":
          description: Invalid ID supplied
        "404":
          description: Listing not found
      x-openapi-router-controller: server.controllers.listings_controller
  /hosts/{hostId}:
    get:
      tags:
      - Hosts
      summary: Find Hosts by ID
      description: Returns a single Host matching the given ID
      operationId: find_host_by_id
      parameters:
      - name: hostId
        in: path
        description: ID of Host to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Host'
                x-content-type: application/json
        "400":
          description: Invalid ID supplied
        "404":
          description: Host not found
      x-openapi-router-controller: server.controllers.hosts_controller
  /layers/crime:
    get:
      tags:
      - Layers
      summary: Retrieve Crime Layer details
      description: Returns details to diyplay Crime Layer (amount per neighbourhood)
      operationId: find_crime_layer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Layer'
              example:
                entries:
                  - latitude: 6.02745618307040320615897144307382404804229736328125
                    longitude: 1.46581298050294517310021547018550336360931396484375
                  - latitude: 6.02745618307040320615897144307382404804229736328125
                    longitude: 1.46581298050294517310021547018550336360931396484375
                type: CRIME_LAYER
        "400":
          description: Invalid ID supplied
        "500":
          description: Internal Server Error
      x-openapi-router-controller: server.controllers.layers_controller
  /layers/complaints:
    get:
      tags:
      - Layers
      summary: Retrieve Complaints Layer details
      description: Returns details to diyplay Complaints Layer (amount per neighbourhood)
      operationId: find_complaints_layer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Layer'
              example:
                entries:
                  - latitude: 6.02745618307040320615897144307382404804229736328125
                    longitude: 1.46581298050294517310021547018550336360931396484375
                  - latitude: 6.02745618307040320615897144307382404804229736328125
                    longitude: 1.46581298050294517310021547018550336360931396484375
                type: COMPLAINT_LAYER
        "500":
          description: Internal Server Error
      x-openapi-router-controller: server.controllers.layers_controller
  /layers/health:
    get:
      tags:
      - Layers
      summary: Retrieve Health Layer details
      description: Returns details to diyplay Health Layer (amount per neighbourhood)
      operationId: find_health_layer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Layer'
              example:
                entries:
                  - latitude: 6.02745618307040320615897144307382404804229736328125
                    longitude: 1.46581298050294517310021547018550336360931396484375
                  - latitude: 6.02745618307040320615897144307382404804229736328125
                    longitude: 1.46581298050294517310021547018550336360931396484375
                type: HEALTH_LAYER
        "500":
          description: Internal Server Error
      x-openapi-router-controller: server.controllers.layers_controller
  /listings/recommendations:
    get:
      tags:
      - Recommendations
      summary: Recommend AirBnBs based on a provided target Listing and filter criteria
      description: Returns a list of recommended Listings based on the provided target Listing and filter criteria
      operationId: recommend_listings
      parameters:
      - name: listingId
        in: query
        description: ID of target Listing to compute similarity
        required: true
        style: form
        explode: true
        schema:
          type: integer
      - name: listingName
        in: query
        description: Name to match Listings (can bei either exact match or not)
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: hostName
        in: query
        description: Name to match Hosts of Listings (can bei either exact match or not)
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: hostId
        in: query
        description: ID of host to match Listings
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: location
        in: query
        description: Filter Listings by their location
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: area
        in: query
        description: Filter Listings by their area
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: priceMin
        in: query
        description: Filter Listings by minimum price
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: priceMax
        in: query
        description: Filter Listings by maximum price
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: minNights
        in: query
        description: Filter Listings by minimum nights
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: availability
        in: query
        description: Filter Listings by their availability
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: listingsPerHost
        in: query
        description: Filter Listings by the number of Listings per Host
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: roomType
        in: query
        description: Filter Listings by room type
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
                x-content-type: application/json
        "500":
          description: Internal Server Error
      x-openapi-router-controller: server.controllers.recommendations_controller
components:
  schemas:
    Listing:
      type: object
      properties:
        id:
          type: integer
          description: Listing ID
          example: 2539
        name:
          type: string
          description: Listing name
          example: My Fancy Room
        host:
          $ref: '#/components/schemas/Host'
        neighbourhood:
          type: string
          description: The neighbourhood in which the Listing is located
          enum:
            - Brooklyn
            - Manhattan
            - Queens
            - Staten Island
            - Bronx
        area:
          type: string
          description: The area in which the Listing is located
          enum:
            - Kensington
            - Bedford-Stuyvesant
            - West Village
            - Fort Greene
            - Crown Heights
            - Inwood
            - Greenpoint
            - East Village
            - South Slope
            - Prospect-Lefferts Gardens
            - Lower East Side
            - SoHo
            - Williamsburg
            - Chelsea
            - Hell's Kitchen
            - Park Slope
            - Clinton Hill
            - Upper East Side
            - Bushwick
            - Prospect Heights
            - Harlem
            - East Harlem
            - Sunnyside
            - St. George
            - Jamaica
            - Middle Village
            - Highbridge
            - Chinatown
            - Upper West Side
            - Tompkinsville
            - Eastchester
            - Little Italy
            - Carroll Gardens
            - Kingsbridge
            - Brooklyn Heights
            - Washington Heights
            - Gowanus
            - Midtown
            - Boerum Hill
            - Nolita
            - Morningside Heights
            - Kips Bay
            - Astoria
            - Theater District
            - Long Island City
            - DUMBO
            - Jackson Heights
            - St. Albans
            - Arrochar
            - Clifton
            - Ridgewood
            - East Flatbush
            - Ozone Park
            - Briarwood
            - Mott Haven
            - Canarsie
            - Tribeca
            - Sunset Park
            - Greenwich Village
            - Concourse
            - Flushing
            - Windsor Terrace
            - Cobble Hill
            - Gramercy
            - Ditmars Steinway
            - Flatlands
            - Murray Hill
            - East Elmhurst
            - Concord
            - Flatbush
            - Bayside
            - Port Morris
            - Fieldston
            - Elmhurst
            - Civic Center
            - Red Hook
            - Bay Ridge
            - Two Bridges
            - Flatiron District
            - Financial District
            - Queens Village
            - Woodside
            - NoHo
            - Midwood
            - Shore Acres
            - East New York
            - Soundview
            - Woodhaven
            - Battery Park City
            - Cypress Hills
            - Bronxdale
            - Sea Gate
            - Rego Park
            - Rockaway Beach
            - Whitestone
            - Richmond Hill
            - Concourse Village
            - Forest Hills
            - Wakefield
            - Stapleton
            - Lighthouse Hill
            - Roosevelt Island
            - Downtown Brooklyn
            - Allerton
            - Jamaica Estates
            - Williamsbridge
            - Bensonhurst
            - Clason Point
            - Mount Hope
            - West Brighton
            - Bay Terrace
            - Far Rockaway
            - Longwood
            - Great Kills
            - Sheepshead Bay
            - Arverne
            - Kew Gardens
            - Gravesend
            - Fort Hamilton
            - Stuyvesant Town
            - East Morrisania
            - Springfield Gardens
            - Borough Park
            - Vinegar Hill
            - Columbia St
            - Hunts Point
            - Pelham Bay
            - City Island
            - Fresh Meadows
            - Todt Hill
            - Howard Beach
            - Laurelton
            - Holliswood
            - Parkchester
            - Corona
            - Brownsville
            - Dyker Heights
            - Marble Hill
            - Rosedale
            - Melrose
            - Norwood
            - Cambria Heights
            - Fordham
            - Richmondtown
            - Maspeth
            - South Ozone Park
            - Manhattan Beach
            - Brighton Beach
            - Kew Gardens Hills
            - Howland Hook
            - Schuylerville
            - Coney Island
            - Claremont Village
            - Randall Manor
            - Midland Beach
            - Jamaica Hills
            - Eltingville
            - Woodlawn
            - Glendale
            - Navy Yard
            - Huguenot
            - Tremont
            - Edenwald
            - Baychester
            - University Heights
            - Bergen Beach
            - Throgs Neck
            - Bellerose
            - Morris Park
            - Westchester Square
            - Riverdale
            - College Point
            - Belmont
            - Douglaston
            - Morris Heights
            - New Springville
            - Pelham Gardens
            - Arden Heights
            - Bath Beach
            - Olinville
            - Grymes Hill
            - Mount Eden
            - Morrisania
            - Hollis
            - Mill Basin
            - New Brighton
            - Bull's Head
            - Dongan Hills
            - Rosebank
            - Van Nest
            - South Beach
            - Mariners Harbor
            - Tottenville
            - North Riverdale
            - Bayswater
        latitude:
          type: number
          description: The exact latitude where the Listing is located
          example: 5.962133916683182377482808078639209270477294921875
        longitude:
          type: number
          description: The exact longitude where the Listing is located
          example:  5.63737665663332876420099637471139430999755859375
        roomType:
          type: string
          description: The type of room which the Listing offers
          enum:
            - Private room
            - Entire home/apt
            - Shared Room
        price:
          type: integer
          description: Price of the Listing
          example: 100
        minNights:
          type: integer
          description: Minimum number of nights that this Listing can be booked for
          example: 1
        numOfReviews:
          type: integer
          description: The amount of reviews for this Listing
          example: 5
        availability:
          type: integer
          description: The availability in days (of a year)
          example: 365
        images:
          type: array
          example: https://example.com/path_to_image_1
          items:
            type: string
      example:
        area: Kensington
        numOfReviews: 9
        minNights: 7
        neighbourhood: Brooklyn
        price: 2
        latitude: 5.962133916683182377482808078639209270477294921875
        name: name
        host:
          name: name
          numOfListings: 1
          id: 6
        id: 0
        availability: 3
        roomType: Private Room
        longitude: 5.63737665663332876420099637471139430999755859375
        images: ['https://example.com/path_to_image_1', 'https://example.com/path_to_image_2']
    Host:
      type: object
      properties:
        id:
          type: integer
          description: Host ID
          example: 1
        name:
          type: string
          description: Host name
          example: John
        numOfListings:
          type: integer
          description: The number of Listings for the Host
          example: 5
      example:
        name: name
        numOfListings: 1
        id: 6
    Review:
      type: object
      properties:
        id:
          type: integer
          description: Review ID
          example: 1
        listingId:
          type: integer
          description: ID of the Listing which this Review refers to
          example: 2539
        text:
          type: string
          description: The content of the Review (text)
          example: Very nice room!
      example:
        id: 0
        listingId: 6
        text: text
    Layer:
      type: object
      properties:
        type:
          type: string
          description: The type of Layer
          enum:
          - CRIME_LAYER
          - COMPLAINT_LAYER
          - HEALTH_LAYER
        entries:
          type: array
          description: List of all LayerEntries for this Layer
          items:
            $ref: '#/components/schemas/LayerEntry'
      example:
        entries:
        - latitude: 6.02745618307040320615897144307382404804229736328125
          longitude: 1.46581298050294517310021547018550336360931396484375
        - latitude: 6.02745618307040320615897144307382404804229736328125
          longitude: 1.46581298050294517310021547018550336360931396484375
        type: CRIME_LAYER
    LayerEntry:
      type: object
      properties:
        latitude:
          type: number
          description: The exact latitude of this LayerEntry
          example: 6.02745618307040320615897144307382404804229736328125
        longitude:
          type: number
          description: The exact longitude of this LayerEntry
          example: 1.46581298050294517310021547018550336360931396484375
      example:
        latitude: 6.02745618307040320615897144307382404804229736328125
        longitude: 1.46581298050294517310021547018550336360931396484375
    ListingsMetadata:
      type: object
      properties:
        minPrice:
          type: integer
          description: The lowest price of all Listings
          example: 1
        maxPrice:
          type: integer
          description: The highest price of all Listings
          example: 1000
        numOfListings:
          type: integer
          description: The total number of Listings
          example: 9705
        areas:
          type: array
          description: All present areas of NYC (see Listing schema for exhaustive list)
          items:
            type: string
        neighbourhoods:
          type: array
          description: All present neighbourhoods of NYC (see Listing schema for exhaustive list)
          items:
            type: string
        roomTypes:
          type: array
          description: All possible room types (see Listing schema for exhaustive list)
          items:
            type: string
        minListingsPerHost:
          type: integer
          description: The minimum number of Listings per Host
          example: 1
        maxListingsPerHost:
          type: integer
          description: The maximum number of Listings per Host
          example: 49
      example:
        minPrice: 20
        maxPrice: 1800
        numOfListings: 10000
        areas: ['West Village', 'Kensington']
        neighbourhoods: ['Brooklyn', 'Queens']
        roomTypes: ['Entire home/apt', 'Private Room']
        minListingsPerHost: 1
        maxListingsPerHost: 10